version: '3.8'
services:
  data-pipeline:
    build: .
    container_name: airbnb-elt-pipeline
    volumes:
      # This maps your local data folder to the container so you keep the output
      - ./data:/app/data